### ISSUE TITLE
BUG: Sometimes edges faces and verts no longer show up.

### ISSUE THREAD

**Issue by frossdelaqrois** [marynate/mesh-tool#63]
After awhile of using tool switching between selection modes edges Verts and polys no longer show up only way to fix seems to be to open another level then re open original level.

**Comment by marynate** [comment]
By default Mesh Tool won't draw verts/edges/faces in Game mode ("G" key), which might cause confusion sometimes.
In 1.1.1 new "Hide Display In Game View" option will be added to enable/disable this behavior.
![image](https://user-images.githubusercontent.com/3735467/35139077-742e121a-fd2c-11e7-965c-23249a84a8d5.png)
